/**
 * @file Data-only control manifest for the Starlight Visual Customizer. No functions, no CSS -
 * `emit-css.js` alone owns how a control id becomes CSS. Every export here must stay
 * JSON-serializable (the UI ships it to the browser, and `state.js` round-trips it through
 * `encodeState`/`decodeState`).
 *
 * Fixed ids (must not be renamed - CORE-IA and the UI import by exact id/shape, per SPEC.md):
 * `page.toc.minLevel`, `page.toc.maxLevel`, `page.pagination`, `page.lastUpdated`,
 * `page.headingLinks`, `page.credits`, `code.theme`, `type.font.body`, `type.font.heading`,
 * `type.font.mono`.
 */

/**
 * @typedef {{
 *  id: string,
 *  group: string,
 *  section: string,
 *  target: string,
 *  label: string,
 *  help?: string,
 *  type: 'range'|'select'|'toggle'|'color'|'font'|'text',
 *  default: any,
 *  min?: number, max?: number, step?: number, unit?: string,
 *  options?: {value: string, label: string}[],
 *  maxLength?: number,   // 'text' controls only (SPEC-C E4)
 *  tier: 1|1.5|2|'build',
 *  modes?: 'both'|'dark'|'light',
 *  showIf?: {id: string, equals: any},
 * }} Control
 */

/** Panel section order. */
export const GROUPS = [
	'Presets',
	'Colors',
	'Typography',
	'Layout',
	'Header',
	'Sidebar',
	'TOC',
	'Content',
	'Components',
	'Code',
	'Footer',
	'Page options',
];

/**
 * Curated Fontsource variable-font list. Every `pkg` below was verified to exist on the npm
 * registry with `npm view <pkg> name` during authoring (2026-09-22). `system` (used as the
 * default value for the three `type.font.*` controls) is intentionally not listed here: it means
 * "no @import, fall back to Starlight's own `--sl-font-system`/`--sl-font-system-mono` stack".
 * @type {{id: string, family: string, pkg: string, category: 'sans'|'serif'|'mono'}[]}
 */
export const FONTS = [
	{ id: 'inter', family: 'Inter', pkg: '@fontsource-variable/inter', category: 'sans' },
	{ id: 'manrope', family: 'Manrope', pkg: '@fontsource-variable/manrope', category: 'sans' },
	{ id: 'work-sans', family: 'Work Sans', pkg: '@fontsource-variable/work-sans', category: 'sans' },
	{ id: 'figtree', family: 'Figtree', pkg: '@fontsource-variable/figtree', category: 'sans' },
	{ id: 'lora', family: 'Lora', pkg: '@fontsource-variable/lora', category: 'serif' },
	{
		id: 'source-serif-4',
		family: 'Source Serif 4',
		pkg: '@fontsource-variable/source-serif-4',
		category: 'serif',
	},
	{
		id: 'playfair-display',
		family: 'Playfair Display',
		pkg: '@fontsource-variable/playfair-display',
		category: 'serif',
	},
	{
		id: 'newsreader',
		family: 'Newsreader',
		pkg: '@fontsource-variable/newsreader',
		category: 'serif',
	},
	{
		id: 'jetbrains-mono',
		family: 'JetBrains Mono',
		pkg: '@fontsource-variable/jetbrains-mono',
		category: 'mono',
	},
	{ id: 'fira-code', family: 'Fira Code', pkg: '@fontsource-variable/fira-code', category: 'mono' },
	{
		id: 'spline-sans-mono',
		family: 'Spline Sans Mono',
		pkg: '@fontsource-variable/spline-sans-mono',
		category: 'mono',
	},
	{
		id: 'red-hat-mono',
		family: 'Red Hat Mono',
		pkg: '@fontsource-variable/red-hat-mono',
		category: 'mono',
	},
];

/** Shared `options` list for the three `type:'font'` controls: every curated font plus 'system'. */
const FONT_OPTIONS = [
	{ value: 'system', label: 'System (no web font)' },
	...FONTS.map((f) => ({ value: f.id, label: `${f.family} (${f.category})` })),
];

/** @type {Control[]} */
export const controls = [
	// ---- Colors ----------------------------------------------------------
	{
		id: 'color.accent.hue',
		group: 'Colors',
		section: 'Palette',
		target: ".sidebar-content a[aria-current='page'], .sl-markdown-content a",
		label: 'Accent hue',
		help: 'OKLCH hue (degrees) fed to the official palette algorithm, alongside chroma.',
		type: 'range',
		default: 269,
		min: 0,
		max: 360,
		step: 1,
		tier: 1,
		modes: 'both',
	},
	{
		id: 'color.accent.chroma',
		group: 'Colors',
		section: 'Palette',
		target: ".sidebar-content a[aria-current='page'], .sl-markdown-content a",
		label: 'Accent chroma',
		type: 'range',
		default: 0.27,
		min: 0,
		max: 0.4,
		step: 0.005,
		tier: 1,
		modes: 'both',
	},
	{
		id: 'color.gray.hue',
		group: 'Colors',
		section: 'Palette',
		target: '.sl-markdown-content p',
		label: 'Gray hue',
		type: 'range',
		default: 270,
		min: 0,
		max: 360,
		step: 1,
		tier: 1,
		modes: 'both',
	},
	{
		id: 'color.gray.chroma',
		group: 'Colors',
		section: 'Palette',
		target: '.sl-markdown-content p',
		label: 'Gray chroma',
		type: 'range',
		default: 0.016,
		min: 0,
		max: 0.1,
		step: 0.001,
		tier: 1,
		modes: 'both',
	},
	{
		id: 'color.hue.orange',
		group: 'Colors',
		section: 'Semantic hues',
		target: '.starlight-aside--caution',
		label: 'Caution hue (orange)',
		help: 'Drives caution asides/badges/cards.',
		type: 'range',
		default: 41,
		min: 0,
		max: 360,
		step: 1,
		tier: 1,
		modes: 'both',
	},
	{
		id: 'color.hue.green',
		group: 'Colors',
		section: 'Semantic hues',
		target: '.sl-badge.success',
		label: 'Success hue (green)',
		type: 'range',
		default: 101,
		min: 0,
		max: 360,
		step: 1,
		tier: 1,
		modes: 'both',
	},
	{
		id: 'color.hue.blue',
		group: 'Colors',
		section: 'Semantic hues',
		target: '.starlight-aside--note',
		label: 'Note hue (blue)',
		type: 'range',
		default: 234,
		min: 0,
		max: 360,
		step: 1,
		tier: 1,
		modes: 'both',
	},
	{
		id: 'color.hue.purple',
		group: 'Colors',
		section: 'Semantic hues',
		target: '.starlight-aside--tip',
		label: 'Tip hue (purple)',
		type: 'range',
		default: 281,
		min: 0,
		max: 360,
		step: 1,
		tier: 1,
		modes: 'both',
	},
	{
		id: 'color.hue.red',
		group: 'Colors',
		section: 'Semantic hues',
		target: '.starlight-aside--danger',
		label: 'Danger hue (red)',
		type: 'range',
		default: 339,
		min: 0,
		max: 360,
		step: 1,
		tier: 1,
		modes: 'both',
	},
	{
		id: 'color.role.bg',
		group: 'Colors',
		section: 'Role overrides',
		target: 'body',
		label: 'Page background (override)',
		help: "'auto' derives from the generated palette (or Starlight's default if colors are untouched).",
		type: 'color',
		default: 'auto',
		tier: 1,
		modes: 'both',
	},
	{
		id: 'color.role.bgNav',
		group: 'Colors',
		section: 'Role overrides',
		target: 'header.header',
		label: 'Header background (override)',
		type: 'color',
		default: 'auto',
		tier: 1,
		modes: 'both',
	},
	{
		id: 'color.role.bgSidebar',
		group: 'Colors',
		section: 'Role overrides',
		target: '.sidebar-pane',
		label: 'Sidebar background (override)',
		type: 'color',
		default: 'auto',
		tier: 1,
		modes: 'both',
	},
	{
		id: 'color.role.text',
		group: 'Colors',
		section: 'Role overrides',
		target: 'body',
		label: 'Body text (override)',
		type: 'color',
		default: 'auto',
		tier: 1,
		modes: 'both',
	},
	{
		id: 'color.role.link',
		group: 'Colors',
		section: 'Role overrides',
		target: '.sl-markdown-content a',
		label: 'Link / accent text (override)',
		help: 'Shares a token with active sidebar item, current TOC entry, and site title.',
		type: 'color',
		default: 'auto',
		tier: 1,
		modes: 'both',
	},
	{
		id: 'color.contrastFloor',
		group: 'Colors',
		section: 'Contrast',
		target: '.sl-markdown-content a',
		label: 'Contrast floor',
		help: 'Minimum WCAG contrast ratio the generated palette is nudged to meet.',
		type: 'select',
		default: 'aa',
		options: [
			{ value: 'aa', label: 'AA (4.5:1)' },
			{ value: 'aaa', label: 'AAA (7:1)' },
		],
		tier: 1,
		modes: 'both',
	},

	// ---- Typography --------------------------------------------------------
	{
		id: 'type.font.body',
		group: 'Typography',
		section: 'Fonts',
		target: '.sl-markdown-content p',
		label: 'Body font',
		type: 'font',
		default: 'system',
		options: FONT_OPTIONS,
		tier: 1,
	},
	{
		id: 'type.font.heading',
		group: 'Typography',
		section: 'Fonts',
		target: '.sl-markdown-content h2',
		label: 'Heading font',
		type: 'font',
		default: 'system',
		options: FONT_OPTIONS,
		tier: 2,
	},
	{
		id: 'type.font.mono',
		group: 'Typography',
		section: 'Fonts',
		target: '.sl-markdown-content code',
		label: 'Mono font',
		type: 'font',
		default: 'system',
		options: FONT_OPTIONS,
		tier: 1,
	},
	{
		id: 'type.baseSize',
		group: 'Typography',
		section: 'Scale',
		target: '.sl-markdown-content p',
		label: 'Base text size',
		type: 'range',
		default: 16,
		min: 14,
		max: 20,
		step: 1,
		unit: 'px',
		tier: 1,
	},
	{
		id: 'type.scaleRatio',
		group: 'Typography',
		section: 'Scale',
		target: '.sl-markdown-content h2',
		label: 'Type scale ratio',
		// P7 (coordinator polish round): technical detail moved out of `help` (user-facing) - generates
		// the whole --sl-text-* ladder (raw steps + headings, both breakpoints) from base size and this ratio.
		help: 'How much bigger each heading level gets compared to the one below it.',
		type: 'range',
		default: 1.2,
		min: 1.1,
		max: 1.5,
		step: 0.01,
		tier: 1,
	},
	{
		id: 'type.bodyLineHeight',
		group: 'Typography',
		section: 'Scale',
		target: '.sl-markdown-content p',
		label: 'Body line height',
		type: 'range',
		default: 1.75,
		min: 1.3,
		max: 2.2,
		step: 0.05,
		tier: 1,
	},
	{
		id: 'type.headingLineHeight',
		group: 'Typography',
		section: 'Headings',
		target: '.sl-markdown-content h2',
		label: 'Heading line height',
		type: 'range',
		default: 1.2,
		min: 1,
		max: 1.6,
		step: 0.05,
		tier: 1,
	},
	{
		id: 'type.headingWeight',
		group: 'Typography',
		section: 'Headings',
		target: '.sl-markdown-content h2',
		label: 'Heading weight',
		type: 'range',
		default: 600,
		min: 300,
		max: 900,
		step: 100,
		tier: 2,
	},
	{
		id: 'type.headingLetterSpacing',
		group: 'Typography',
		section: 'Headings',
		target: '.sl-markdown-content h2',
		label: 'Heading letter spacing',
		type: 'range',
		default: 0,
		min: -0.02,
		max: 0.12,
		step: 0.005,
		unit: 'em',
		tier: 2,
	},
	{
		id: 'type.headingCase',
		group: 'Typography',
		section: 'Headings',
		target: '.sl-markdown-content h2',
		label: 'Heading case',
		type: 'select',
		default: 'none',
		options: [
			{ value: 'none', label: 'As written' },
			{ value: 'uppercase', label: 'UPPERCASE' },
			{ value: 'capitalize', label: 'Capitalize Each Word' },
		],
		tier: 2,
	},

	// ---- Layout --------------------------------------------------------
	{
		id: 'layout.contentWidth',
		group: 'Layout',
		section: 'Dimensions',
		target: '.main-pane .sl-container',
		label: 'Content width',
		type: 'range',
		default: 45,
		min: 30,
		max: 70,
		step: 1,
		unit: 'rem',
		tier: 1,
	},
	{
		id: 'layout.sidebarWidth',
		group: 'Layout',
		section: 'Dimensions',
		target: '.sidebar-pane',
		label: 'Sidebar width',
		type: 'range',
		default: 18.75,
		min: 12,
		max: 28,
		step: 0.25,
		unit: 'rem',
		tier: 1,
	},
	{
		id: 'layout.navHeight',
		group: 'Layout',
		section: 'Dimensions',
		target: 'header.header',
		label: 'Header height',
		help: "Overrides Starlight's own responsive step-up to a single fixed height at all widths.",
		type: 'range',
		default: 3.5,
		min: 3,
		max: 6,
		step: 0.25,
		unit: 'rem',
		tier: 1,
	},
	{
		id: 'layout.contentGapY',
		group: 'Layout',
		section: 'Dimensions',
		target: '.sl-markdown-content p',
		label: 'Content vertical rhythm',
		type: 'range',
		default: 1,
		min: 0.5,
		max: 3,
		step: 0.25,
		unit: 'rem',
		tier: 1,
	},
	{
		id: 'layout.contentPadX',
		group: 'Layout',
		section: 'Dimensions',
		target: '.content-panel',
		label: 'Content gutters',
		// P7: technical detail moved out of `help` - overrides Starlight's own --sl-content-pad-x,
		// which normally widens slightly (1rem to 1.5rem) at the 72rem breakpoint; this control sets
		// one fixed value at every width instead (the same trade-off layout.navHeight makes for
		// --sl-nav-height, and header.titleSize for --sl-text-h4).
		help: 'Side padding around the page content. Stays the same at every screen size, even though Starlight itself widens it slightly on large screens.',
		type: 'range',
		default: 1,
		min: 0.5,
		max: 3,
		step: 0.25,
		unit: 'rem',
		tier: 1,
	},
	{
		id: 'layout.radius',
		group: 'Layout',
		section: 'Shape',
		target: ".sidebar-content a[aria-current='page']",
		label: 'Global corner radius',
		// P7: technical detail moved out of `help` - drives every Tier-2 radius (sidebar pill, search
		// trigger, pagination cards, code frame, tabs, asides) via --svc-radius. Default (6px) is a
		// no-op placeholder, not Starlight's own per-component radius, so 0 is a deliberate choice.
		help: 'Corner roundness across the sidebar, search box, pagination cards, code blocks, tabs and asides. Use 0 for sharp corners.',
		type: 'range',
		default: 6,
		min: 0,
		max: 24,
		step: 1,
		unit: 'px',
		tier: 1,
	},
	{
		id: 'layout.shadowElevation',
		group: 'Layout',
		section: 'Shape',
		target: '.pagination-links a',
		label: 'Shadow elevation',
		type: 'select',
		default: 'default',
		options: [
			{ value: 'none', label: 'Flat (no shadows)' },
			{ value: 'soft', label: 'Soft' },
			{ value: 'default', label: 'Default' },
			{ value: 'strong', label: 'Strong' },
		],
		tier: 1,
	},
	{
		id: 'layout.contentAlign',
		group: 'Layout',
		section: 'Content column',
		target: '.main-pane .sl-container',
		label: 'Content column alignment',
		// P7: technical detail moved out of `help` - overrides how the content column sits inside its
		// available space at the TOC breakpoint (>=72rem). Default matches Starlight's own behavior:
		// hugs the TOC when a TOC exists.
		help: 'Where the page content sits between the sidebar and the outline, on wide screens.',
		type: 'select',
		default: 'default',
		options: [
			{ value: 'default', label: "Default (hugs the TOC)" },
			{ value: 'start', label: 'Hug the sidebar' },
			{ value: 'center', label: 'Center' },
		],
		tier: 2,
	},

	// ---- Header --------------------------------------------------------
	{
		id: 'header.style',
		group: 'Header',
		section: 'Bar',
		target: 'header.header',
		label: 'Header style',
		type: 'select',
		default: 'default',
		options: [
			{ value: 'default', label: 'Default border' },
			{ value: 'no-border', label: 'No border' },
			{ value: 'shadow', label: 'Shadow' },
			{ value: 'translucent-blur', label: 'Translucent blur' },
		],
		tier: 2,
	},
	{
		id: 'header.titleSize',
		group: 'Header',
		section: 'Bar',
		target: '.site-title',
		label: 'Site title size',
		// P7: technical detail moved out of `help` - overrides the site title's own responsive
		// step-up (--sl-text-h4, which bumps at the 50em breakpoint) to a single fixed size at every
		// width, the same trade-off layout.navHeight makes for --sl-nav-height.
		help: "Sets the site title's text size. Stays the same at every screen width, even though Starlight itself bumps it up on larger screens.",
		type: 'range',
		default: 1.25,
		min: 0.875,
		max: 2,
		step: 0.125,
		unit: 'rem',
		tier: 2,
	},
	{
		id: 'header.searchTriggerStyle',
		group: 'Header',
		section: 'Search box',
		target: 'button[data-open-modal]',
		label: 'Search trigger style',
		help: 'Applies at the desktop breakpoint (>=50rem), matching where Starlight itself styles the trigger as a button rather than a bare icon.',
		type: 'select',
		default: 'default',
		options: [
			{ value: 'default', label: 'Default' },
			{ value: 'pill', label: 'Pill' },
			{ value: 'underline', label: 'Underline' },
			{ value: 'ghost', label: 'Ghost' },
		],
		tier: 2,
	},
	{
		id: 'header.searchAlign',
		group: 'Header',
		section: 'Search box',
		target: '.header > div:has(> site-search)',
		label: 'Search box alignment',
		help: 'Applies at the desktop breakpoint (>=50rem), where the search box becomes its own header grid column.',
		type: 'select',
		default: 'default',
		options: [
			{ value: 'default', label: 'Default (aligned to content column)' },
			{ value: 'center', label: 'Center' },
			{ value: 'end', label: 'End' },
			{ value: 'stretch', label: 'Stretch (fills the column)' },
		],
		tier: 2,
	},
	{
		id: 'header.searchWidth',
		group: 'Header',
		section: 'Search box',
		target: 'button[data-open-modal]',
		label: 'Search box width',
		help: "Overrides the search trigger's own 22rem cap at the desktop breakpoint (>=50rem); below it the trigger is a bare icon with no width to set.",
		type: 'range',
		default: 22,
		min: 14,
		max: 32,
		step: 1,
		unit: 'rem',
		tier: 2,
	},
	{
		id: 'header.searchShortcut',
		group: 'Header',
		section: 'Search box',
		target: "button[data-open-modal] > kbd",
		label: 'Keyboard shortcut hint',
		help: "Shows or hides the \"Ctrl K\" hint inside the search trigger (desktop only - Starlight never renders it below 50rem).",
		type: 'toggle',
		default: true,
		tier: 2,
	},
	// SPEC-C E4: build-time only (no live CSS - the header renders your project's real title via
	// Astro props, so the preview sets `.site-title span`'s text directly instead). Empty string
	// (the manifest default) means "keep your project's own title" - `emitApplyTheme` only adds a
	// `title:` config line when this is non-empty, and the preview only overrides the DOM text then.
	{
		id: 'site.title',
		group: 'Header',
		section: 'Site title',
		target: '.site-title',
		label: 'Site title text',
		help: "Leave blank to keep your project's own title. Applied to your Starlight config at export time, not to theme.css.",
		type: 'text',
		default: '',
		maxLength: 60,
		tier: 'build',
	},

	// ---- Sidebar --------------------------------------------------------
	{
		id: 'sidebar.activeStyle',
		group: 'Sidebar',
		section: 'Items',
		target: ".sidebar-content a[aria-current='page']",
		label: 'Active item style',
		type: 'select',
		default: 'filled-pill',
		options: [
			{ value: 'filled-pill', label: 'Filled pill (default)' },
			{ value: 'tinted', label: 'Tinted' },
			{ value: 'left-bar', label: 'Left bar' },
			{ value: 'text-only', label: 'Text only' },
		],
		tier: 2,
	},
	{
		id: 'sidebar.itemPaddingY',
		group: 'Sidebar',
		section: 'Items',
		target: '.sidebar-content a',
		label: 'Item vertical padding',
		// P7: technical detail moved out of `help` - Starlight's own sidebar link padding is 0.3em
		// (font-relative, so it already scales with each row's own text size); this control expresses
		// the same unit so the default stays exact.
		help: "Vertical space inside each sidebar link. Scales with the sidebar text size, matching Starlight's default.",
		type: 'range',
		default: 0.3,
		min: 0.1,
		max: 0.8,
		step: 0.05,
		unit: 'em',
		tier: 2,
	},
	{
		id: 'sidebar.hoverTint',
		group: 'Sidebar',
		section: 'Items',
		// Not `:hover` - a manifest `target` names the affected on-page element for scroll-to/
		// highlight and the visibility probe (tests/e2e/targets.mjs); it doesn't need to already show
		// the hover-only effect. The actual CSS this control emits is scoped to `:hover`/`:focus`
		// (see treatments applied in emit-css.js).
		target: ".sidebar-content a:not([aria-current='page'])",
		label: 'Tint on hover',
		help: 'Adds a subtle background tint on hover for non-active sidebar links (Starlight only changes their text color by default).',
		type: 'toggle',
		default: false,
		tier: 2,
	},
	{
		id: 'sidebar.nestIndent',
		group: 'Sidebar',
		section: 'Nesting',
		target: '.sidebar-content ul ul li',
		label: 'Nesting indent',
		// P7: technical detail moved out of `help` - overrides the fixed 1rem-per-level indent under a
		// collapsed group (Starlight reuses --sl-sidebar-item-padding-inline for this; this control sets
		// the indent alone, leaving every row's own horizontal padding untouched).
		help: "How far a nested group's items shift right, one step per level. Each item's own padding is unchanged.",
		type: 'range',
		default: 1,
		min: 0.5,
		max: 2,
		step: 0.125,
		unit: 'rem',
		tier: 2,
	},
	{
		id: 'sidebar.nestGuides',
		group: 'Sidebar',
		section: 'Nesting',
		target: '.sidebar-content ul ul li',
		label: 'Nested guide lines',
		help: 'Starlight already draws a thin line down the left edge of a nested group by default; turn this off to remove it.',
		type: 'toggle',
		default: true,
		tier: 2,
	},
	{
		id: 'sidebar.groupLabelStyle',
		group: 'Sidebar',
		section: 'Groups',
		target: '.sidebar-content .group-label .large',
		label: 'Group label style',
		type: 'select',
		default: 'default',
		options: [
			{ value: 'default', label: 'Default' },
			{ value: 'small-caps', label: 'Small caps' },
			{ value: 'muted-uppercase', label: 'Muted uppercase' },
			{ value: 'divider', label: 'Divider line' },
		],
		tier: 2,
	},

	// ---- TOC --------------------------------------------------------
	{
		id: 'toc.currentItemStyle',
		group: 'TOC',
		section: 'Current item',
		target: "starlight-toc a[aria-current='true']",
		label: 'Current item style',
		type: 'select',
		default: 'default',
		options: [
			{ value: 'default', label: 'Default (color only)' },
			{ value: 'left-bar', label: 'Left bar' },
			{ value: 'tint', label: 'Background tint' },
			{ value: 'dot', label: 'Dot marker' },
		],
		tier: 2,
	},
	{
		id: 'toc.textSize',
		group: 'TOC',
		section: 'Outline',
		target: 'starlight-toc a',
		label: 'Outline text size',
		// P7: technical detail moved out of `help` - Starlight's TOC links use --sl-text-xs (via
		// PageSidebar.astro's ambient link rule) with no dedicated token of their own.
		help: "Text size for the outline's links.",
		type: 'range',
		default: 0.8125,
		min: 0.6875,
		max: 1.125,
		step: 0.0625,
		unit: 'rem',
		tier: 2,
	},
	{
		id: 'toc.indent',
		group: 'TOC',
		section: 'Outline',
		target: 'starlight-toc a',
		label: 'Heading indent',
		// P7: technical detail moved out of `help` - overrides the fixed 1rem-per-depth-level indent
		// step. The "Dot marker" current-item style computes its own dot position from the stock 1rem
		// step, so combining it with a customized indent here leaves the CURRENT item's own indent at
		// the dot's own formula (documented trade-off, keeps the dot aligned with its own text).
		help: "How far each outline level shifts right. With the Dot marker style, the current item's own indent stays fixed so its dot lines up.",
		type: 'range',
		default: 1,
		min: 0.5,
		max: 2,
		step: 0.125,
		unit: 'rem',
		tier: 2,
	},
	{
		id: 'toc.depthGuides',
		group: 'TOC',
		section: 'Outline',
		target: 'starlight-toc li li a',
		label: 'Depth guide lines',
		help: 'Adds a thin left-edge line to nested (depth 2+) outline entries. Starlight draws no such line by default.',
		type: 'toggle',
		default: false,
		tier: 2,
	},
	{
		id: 'toc.position',
		group: 'TOC',
		section: 'Placement',
		target: '.right-sidebar-container',
		label: 'TOC placement',
		// P7: technical detail moved out of `help` - applies at the TOC breakpoint (>=72rem); "Left"
		// moves the rail between the sidebar and the content column and flips its divider to the other
		// side; F5 (SPEC-C phase 3, point 12): "Right edge of window" pins the rail to the window's own
		// right edge on wide screens instead of wherever the centered content column happens to end.
		help: 'On wide screens only. "Left" moves the outline between the sidebar and the page content; "Right edge of window" pins it to the window instead of the content column.',
		type: 'select',
		default: 'right',
		options: [
			{ value: 'right', label: 'Right (default)' },
			{ value: 'left', label: 'Left' },
			{ value: 'window-right', label: 'Right edge of window' },
		],
		tier: 2,
	},

	// ---- Content --------------------------------------------------------
	{
		id: 'content.asideStyle',
		group: 'Content',
		section: 'Callouts',
		target: '.starlight-aside',
		label: 'Aside (callout) style',
		type: 'select',
		default: 'default',
		options: [
			{ value: 'default', label: 'Left bar (default)' },
			{ value: 'full-border', label: 'Full border' },
			{ value: 'filled', label: 'Filled' },
			{ value: 'minimal', label: 'Minimal' },
		],
		tier: 2,
	},
	{
		id: 'content.asidePadding',
		group: 'Content',
		section: 'Callouts',
		target: '.starlight-aside',
		label: 'Callout padding',
		type: 'range',
		default: 1,
		min: 0.25,
		max: 2.5,
		step: 0.25,
		unit: 'rem',
		tier: 2,
	},
	{
		id: 'content.headingDivider',
		group: 'Content',
		section: 'Headings',
		target: '.sl-markdown-content h2:not(:where(.not-content *))',
		label: 'Rule under H2',
		help: 'Adds a thin bottom border under every level-2 heading. Starlight has no border there by default.',
		type: 'toggle',
		default: false,
		tier: 2,
	},
	{
		id: 'content.inlineCodeStyle',
		group: 'Content',
		section: 'Inline code',
		target: ".sl-markdown-content code:not(:where(.not-content *)):not(pre code)",
		label: 'Inline code style',
		type: 'select',
		default: 'default',
		options: [
			{ value: 'default', label: 'Default' },
			{ value: 'rounded', label: 'Rounded' },
			{ value: 'outlined', label: 'Outlined' },
			{ value: 'accent-tinted', label: 'Accent tinted' },
		],
		tier: 2,
	},
	{
		id: 'content.linkStyle',
		group: 'Content',
		section: 'Links',
		target: '.sl-markdown-content a:not(:where(.not-content *))',
		label: 'Link style',
		type: 'select',
		default: 'default',
		options: [
			{ value: 'default', label: 'Underlined, accent color (default)' },
			{ value: 'no-underline', label: 'No underline (underline on hover)' },
			{ value: 'thick-offset', label: 'Thick offset underline' },
			{ value: 'accent-bg-hover', label: 'Accent background on hover' },
		],
		tier: 2,
	},
	{
		id: 'content.tableStyle',
		group: 'Content',
		section: 'Tables',
		target: '.sl-markdown-content table:not(:where(.not-content *))',
		label: 'Table style',
		type: 'select',
		default: 'default',
		options: [
			{ value: 'default', label: 'Default' },
			{ value: 'striped', label: 'Striped rows' },
			{ value: 'bordered', label: 'Bordered cells' },
			{ value: 'header-fill', label: 'Filled header' },
		],
		tier: 2,
	},
	{
		id: 'content.tableCellPadding',
		group: 'Content',
		section: 'Tables',
		target: '.sl-markdown-content :is(th, td):not(:where(.not-content *))',
		label: 'Table cell padding',
		help: 'Vertical padding only - the horizontal 1rem and the zeroed first/last-column edges are left exactly as Starlight sets them.',
		type: 'range',
		default: 0.5,
		min: 0.125,
		max: 1.5,
		step: 0.125,
		unit: 'rem',
		tier: 2,
	},
	{
		id: 'content.blockquoteStyle',
		group: 'Content',
		section: 'Blockquotes',
		target: '.sl-markdown-content blockquote:not(:where(.not-content *))',
		label: 'Blockquote style',
		type: 'select',
		default: 'default',
		options: [
			{ value: 'default', label: 'Left bar (default)' },
			{ value: 'soft-fill', label: 'Soft fill' },
			{ value: 'editorial', label: 'Editorial' },
			{ value: 'minimal', label: 'Minimal' },
		],
		tier: 2,
	},
	{
		id: 'content.titleAlign',
		group: 'Content',
		section: 'Page title',
		target: '.sl-container > h1#_top',
		label: 'Page title alignment',
		help: 'The regular (non-splash) page title only; the splash hero title is controlled separately below.',
		type: 'select',
		default: 'start',
		options: [
			{ value: 'start', label: 'Start (default)' },
			{ value: 'center', label: 'Center' },
		],
		tier: 2,
	},
	{
		id: 'content.heroAlign',
		group: 'Content',
		section: 'Splash hero',
		target: '.hero',
		label: 'Splash hero alignment',
		help: "Only applies to pages using the splash template's hero (e.g. the home page).",
		type: 'select',
		default: 'default',
		options: [
			{ value: 'default', label: "Default (Starlight's layout)" },
			{ value: 'center', label: 'Center (stacked, centered)' },
			{ value: 'start', label: 'Start (text left-aligned, image right)' },
		],
		tier: 2,
	},

	// ---- Components --------------------------------------------------------
	{
		id: 'components.tabsIndicatorStyle',
		group: 'Components',
		section: 'Tabs',
		target: "starlight-tabs [role='tablist']",
		label: 'Tabs indicator style',
		type: 'select',
		default: 'underline',
		options: [
			{ value: 'underline', label: 'Underline (default)' },
			{ value: 'pill', label: 'Pill' },
			{ value: 'segmented', label: 'Segmented' },
		],
		tier: 2,
	},
	{
		id: 'components.cardStyle',
		group: 'Components',
		section: 'Cards',
		target: 'article.card',
		label: 'Card style',
		type: 'select',
		default: 'default',
		options: [
			{ value: 'default', label: 'Default (outlined)' },
			{ value: 'elevated', label: 'Elevated' },
			{ value: 'flat', label: 'Flat' },
		],
		tier: 2,
	},
	{
		id: 'components.linkButtonStyle',
		group: 'Components',
		section: 'Buttons',
		target: '.sl-link-button',
		label: 'Link button style',
		help: "Starlight's <LinkButton> is already a full pill (border-radius: 999rem) by default.",
		type: 'select',
		default: 'default',
		options: [
			{ value: 'default', label: 'Pill (default)' },
			{ value: 'soft', label: 'Soft corners' },
			{ value: 'square', label: 'Square' },
		],
		tier: 2,
	},
	{
		id: 'components.badgeStyle',
		group: 'Components',
		section: 'Badges',
		target: '.sl-badge',
		label: 'Badge style',
		type: 'select',
		default: 'default',
		options: [
			{ value: 'default', label: 'Default' },
			{ value: 'pill', label: 'Pill' },
			{ value: 'square', label: 'Square' },
			{ value: 'outline', label: 'Outline' },
		],
		tier: 2,
	},

	// ---- Code --------------------------------------------------------
	{
		id: 'code.frameRadius',
		group: 'Code',
		section: 'Frame',
		target: '.expressive-code .frame',
		label: 'Code frame radius',
		// P7: technical detail moved out of `help` - best-effort override of the Expressive Code
		// frame via --ec-brdRad.
		help: "Corner roundness of the code block's outer frame.",
		type: 'range',
		default: 0,
		min: 0,
		max: 16,
		step: 1,
		unit: 'px',
		tier: 1.5,
	},
	{
		id: 'code.fontSize',
		group: 'Code',
		section: 'Text',
		target: '.expressive-code pre code',
		label: 'Code font size',
		// P7: technical detail moved out of `help` - Expressive Code's own --ec-codeFontSize, which
		// defaults to Starlight's --sl-text-code (= --sl-text-sm).
		help: 'Text size inside code blocks.',
		type: 'range',
		default: 0.875,
		min: 0.6875,
		max: 1.125,
		step: 0.0625,
		unit: 'rem',
		tier: 1.5,
	},
	{
		id: 'code.wrap',
		group: 'Code',
		section: 'Wrapping',
		target: '.expressive-code pre',
		label: 'Wrap long lines',
		// P7: technical detail moved out of `help` - build-time only (Expressive Code's own
		// defaultProps.wrap): applied through APPLY-THEME.md, approximated live here with the same CSS
		// Expressive Code's real .wrap class uses.
		help: 'Wraps long code lines instead of scrolling sideways. Applied when you export; the preview approximates it live.',
		type: 'toggle',
		default: false,
		tier: 'build',
	},
	{
		id: 'code.theme',
		group: 'Code',
		section: 'Theme',
		target: '.expressive-code',
		label: 'Expressive Code theme',
		help: 'Build-time only; the preview shows a note rather than swapping syntax colors live.',
		type: 'select',
		default: 'starlight-default',
		options: [
			{ value: 'starlight-default', label: 'Starlight default (night-owl)' },
			{ value: 'github', label: 'GitHub' },
			{ value: 'catppuccin', label: 'Catppuccin' },
			{ value: 'dracula', label: 'Dracula' },
			{ value: 'nord', label: 'Nord' },
			{ value: 'min', label: 'Min' },
		],
		tier: 'build',
	},

	// ---- Footer --------------------------------------------------------
	{
		id: 'footer.paginationStyle',
		group: 'Footer',
		section: 'Pagination',
		target: '.pagination-links a',
		label: 'Pagination style',
		type: 'select',
		default: 'cards',
		options: [
			{ value: 'cards', label: 'Cards (default)' },
			{ value: 'minimal-links', label: 'Minimal links' },
			{ value: 'full-width-bar', label: 'Full-width bar' },
		],
		tier: 2,
	},
	{
		id: 'footer.paginationAlign',
		group: 'Footer',
		section: 'Pagination',
		target: '.pagination-links',
		label: 'Pagination alignment',
		type: 'select',
		default: 'default',
		options: [
			{ value: 'default', label: 'Default' },
			{ value: 'center', label: 'Center (shrink-wrapped cards)' },
			{ value: 'stretch', label: 'Stretch (spread card contents)' },
		],
		tier: 2,
	},
	{
		id: 'footer.paginationShadow',
		group: 'Footer',
		section: 'Pagination',
		target: '.pagination-links a',
		label: 'Pagination card shadow',
		help: 'Pagination cards carry a soft drop shadow by default.',
		type: 'toggle',
		default: true,
		tier: 2,
	},

	// ---- Page options (build-time; approximated in preview) ------------
	{
		id: 'page.toc.minLevel',
		group: 'Page options',
		section: 'Table of contents',
		target: 'starlight-toc',
		label: 'TOC min heading level',
		type: 'range',
		default: 2,
		min: 1,
		max: 6,
		step: 1,
		tier: 'build',
	},
	{
		id: 'page.toc.maxLevel',
		group: 'Page options',
		section: 'Table of contents',
		target: 'starlight-toc',
		label: 'TOC max heading level',
		type: 'range',
		default: 3,
		min: 1,
		max: 6,
		step: 1,
		tier: 'build',
	},
	{
		id: 'page.pagination',
		group: 'Page options',
		section: 'Page metadata',
		target: '.pagination-links',
		label: 'Prev/next pagination',
		type: 'toggle',
		default: true,
		tier: 'build',
	},
	{
		id: 'page.lastUpdated',
		group: 'Page options',
		section: 'Page metadata',
		target: '.meta',
		label: 'Show last updated',
		type: 'toggle',
		default: false,
		tier: 'build',
	},
	{
		id: 'page.headingLinks',
		group: 'Page options',
		section: 'Page metadata',
		target: '.sl-anchor-link',
		label: 'Heading anchor links',
		type: 'toggle',
		default: true,
		tier: 'build',
	},
	{
		id: 'page.credits',
		group: 'Page options',
		section: 'Page metadata',
		target: 'footer .kudos, footer',
		label: 'Starlight credits link',
		type: 'toggle',
		default: false,
		tier: 'build',
	},
];
