/**
 * @file Preset list. `starlight-default` (empty values - the fidelity baseline) plus the official
 * theme designer's 5 accent/gray presets (exact hue/chroma values ported from the `presets`
 * object in withastro/starlight `docs/src/components/theme-designer/store.ts`, MIT) plus 4
 * "character" presets that each
 * set colors + fonts + several treatments + radius so they read as clearly different themes.
 *
 * The reference's own `default` preset is intentionally omitted: its values equal the manifest
 * defaults (Starlight's real look), so it would duplicate `starlight-default` in the gallery.
 */

/** @typedef {{id: string, label: string, description: string, values: Record<string, any>}} Preset */

/** @type {Preset[]} */
export const presets = [
	{
		id: 'starlight-default',
		label: 'Starlight default',
		description: "No overrides - Starlight's own built-in HSL theme.",
		values: {},
	},

	// ---- Official theme designer presets (withastro/starlight docs/src/components/theme-designer/store.ts) ----
	{
		id: 'ocean',
		label: 'Designer: Ocean',
		description: 'Official theme designer preset.',
		values: {
			'color.accent.hue': 240,
			'color.accent.chroma': 0.27,
			'color.gray.hue': 220,
			'color.gray.chroma': 0.025,
		},
	},
	{
		id: 'forest',
		label: 'Designer: Forest',
		description: 'Official theme designer preset.',
		values: {
			'color.accent.hue': 140,
			'color.accent.chroma': 0.27,
			'color.gray.hue': 140,
			'color.gray.chroma': 0.03,
		},
	},
	{
		id: 'oxide',
		label: 'Designer: Oxide',
		description: 'Official theme designer preset.',
		values: {
			'color.accent.hue': 30,
			'color.accent.chroma': 0.27,
			'color.gray.hue': 30,
			'color.gray.chroma': 0.02,
		},
	},
	{
		id: 'nebula',
		label: 'Designer: Nebula',
		description: 'Official theme designer preset.',
		values: {
			'color.accent.hue': 320,
			'color.accent.chroma': 0.27,
			'color.gray.hue': 305,
			'color.gray.chroma': 0.07,
		},
	},

	// ---- Character presets: colors + fonts + several treatments + radius ----
	{
		id: 'editorial-serif',
		label: 'Editorial Serif',
		description: 'Warm serif body/heading pairing, generous rhythm, understated treatments.',
		values: {
			'color.accent.hue': 20,
			'color.accent.chroma': 0.15,
			'color.gray.hue': 40,
			'color.gray.chroma': 0.015,
			'type.font.body': 'source-serif-4',
			'type.font.heading': 'playfair-display',
			'type.font.mono': 'jetbrains-mono',
			'type.baseSize': 18,
			'type.scaleRatio': 1.333,
			'type.bodyLineHeight': 1.8,
			'type.headingLineHeight': 1.15,
			'type.headingWeight': 700,
			'layout.contentWidth': 42,
			'layout.contentGapY': 1.5,
			'layout.radius': 2,
			'sidebar.activeStyle': 'text-only',
			'sidebar.groupLabelStyle': 'small-caps',
			'sidebar.itemPaddingY': 0.45,
			'content.linkStyle': 'thick-offset',
			'content.asideStyle': 'minimal',
			'content.blockquoteStyle': 'editorial',
			'content.headingDivider': true,
			'toc.textSize': 0.9,
			'footer.paginationStyle': 'minimal-links',
		},
	},
	{
		id: 'dense-technical',
		label: 'Dense Technical',
		description: 'Compact monospace-leaning reference theme: small type, tight rhythm, bordered surfaces.',
		values: {
			'color.accent.hue': 199,
			'color.accent.chroma': 0.19,
			'color.gray.hue': 220,
			'color.gray.chroma': 0.01,
			'type.font.body': 'work-sans',
			'type.font.heading': 'work-sans',
			'type.font.mono': 'jetbrains-mono',
			'type.baseSize': 14,
			'type.scaleRatio': 1.125,
			'type.bodyLineHeight': 1.5,
			'type.headingLineHeight': 1.1,
			'type.headingWeight': 700,
			'type.headingCase': 'uppercase',
			'type.headingLetterSpacing': 0.02,
			'layout.contentWidth': 55,
			'layout.contentGapY': 0.75,
			'layout.radius': 0,
			'layout.shadowElevation': 'none',
			'sidebar.activeStyle': 'left-bar',
			'sidebar.itemPaddingY': 0.2,
			'toc.currentItemStyle': 'left-bar',
			'toc.textSize': 0.75,
			'content.tableStyle': 'bordered',
			'content.tableCellPadding': 0.3125,
			'content.inlineCodeStyle': 'outlined',
			'content.asideStyle': 'full-border',
			'components.tabsIndicatorStyle': 'segmented',
			'components.cardStyle': 'flat',
			'components.badgeStyle': 'square',
			'code.frameRadius': 0,
			'code.fontSize': 0.8125,
			'footer.paginationShadow': false,
		},
	},
	{
		id: 'soft-rounded',
		label: 'Soft Rounded',
		description: 'Friendly, high-radius theme with tinted surfaces and pill shapes throughout.',
		values: {
			'color.accent.hue': 320,
			'color.accent.chroma': 0.16,
			'color.gray.hue': 300,
			'color.gray.chroma': 0.02,
			'type.font.body': 'manrope',
			'type.font.heading': 'figtree',
			'type.font.mono': 'red-hat-mono',
			'type.baseSize': 17,
			'type.scaleRatio': 1.2,
			'type.headingWeight': 800,
			'layout.radius': 18,
			'layout.shadowElevation': 'soft',
			'sidebar.activeStyle': 'tinted',
			'sidebar.hoverTint': true,
			'toc.currentItemStyle': 'tint',
			'header.style': 'no-border',
			'header.searchTriggerStyle': 'pill',
			'content.asideStyle': 'filled',
			'content.inlineCodeStyle': 'rounded',
			'content.blockquoteStyle': 'soft-fill',
			'components.tabsIndicatorStyle': 'pill',
			'components.cardStyle': 'elevated',
			'components.badgeStyle': 'pill',
			'footer.paginationStyle': 'cards',
			'code.frameRadius': 12,
		},
	},
	{
		id: 'high-contrast-mono',
		label: 'High Contrast Mono',
		description: 'Sharp corners, AAA contrast floor, monospace body copy, flat shadows.',
		values: {
			'color.accent.hue': 0,
			'color.accent.chroma': 0,
			'color.gray.hue': 0,
			'color.gray.chroma': 0,
			'color.contrastFloor': 'aaa',
			'type.font.body': 'jetbrains-mono',
			'type.font.heading': 'jetbrains-mono',
			'type.font.mono': 'jetbrains-mono',
			'type.baseSize': 16,
			'type.scaleRatio': 1.15,
			'type.headingCase': 'uppercase',
			'type.headingWeight': 700,
			'layout.radius': 0,
			'layout.shadowElevation': 'none',
			'header.style': 'no-border',
			'sidebar.activeStyle': 'left-bar',
			'toc.currentItemStyle': 'left-bar',
			'content.linkStyle': 'thick-offset',
			'content.tableStyle': 'bordered',
			'content.inlineCodeStyle': 'outlined',
			'content.asideStyle': 'full-border',
			'content.blockquoteStyle': 'minimal',
			'components.tabsIndicatorStyle': 'segmented',
			'components.cardStyle': 'flat',
			'components.linkButtonStyle': 'square',
			'components.badgeStyle': 'outline',
			'footer.paginationStyle': 'minimal-links',
			'footer.paginationShadow': false,
			'code.frameRadius': 0,
		},
	},
];
